import React, { useState, useEffect } from 'react';
import { HashRouter, Route, Routes, useParams, useNavigate, Navigate } from 'react-router-dom';
import { PartyState, Guest } from './types';
import { createParty, getParty, joinParty, subscribeToParty } from './services/partyService';
import { HostDashboard } from './components/HostDashboard';
import { GuestVoting } from './components/GuestVoting';
import { Info } from 'lucide-react';

// --- Layout Component ---
const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div className="min-h-screen bg-board-light text-stone-800 font-sans selection:bg-accent selection:text-white">
    <header className="bg-white border-b border-stone-200 py-4 shadow-sm sticky top-0 z-50">
      <div className="container mx-auto px-4 flex justify-between items-center">
        <div className="flex items-center text-stone-800">
           <span className="font-serif text-2xl font-bold tracking-tight">Charcuterie<span className="text-accent">Voter</span></span>
        </div>
      </div>
    </header>
    
    <main className="container mx-auto px-4 py-8">
      {children}
    </main>
    <footer className="bg-stone-100 border-t border-stone-200 py-8 mt-12">
      <div className="container mx-auto px-4 text-center text-stone-500 text-sm">
        <p>© {new Date().getFullYear()} CharcuterieVoter. Designed for delicious gatherings.</p>
        <p className="mt-2 text-xs text-stone-400">Pencil sketches generated by Gemini AI.</p>
      </div>
    </footer>
  </div>
);

// --- Landing Page ---
const Landing = () => {
  const [hostName, setHostName] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const handleStart = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!hostName.trim()) return;
    
    setIsLoading(true);
    try {
      const party = await createParty(hostName);
      navigate(`/party/${party.id}`);
    } catch (e) {
      console.error(e);
      alert("Error creating party. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center py-20">
      <div className="text-center max-w-2xl mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <h1 className="font-serif text-5xl md:text-6xl font-bold text-stone-900 mb-6 leading-tight">
          The Art of the <br/>
          <span className="text-accent italic">Perfect Board</span>
        </h1>
        <p className="text-xl text-stone-600 leading-relaxed">
          Stop guessing what your guests eat. Create a party, invite your friends, 
          and let them vote on their favorite meats, cheeses, and pairings.
        </p>
      </div>

      <form onSubmit={handleStart} className="w-full max-w-md bg-white p-8 rounded-2xl shadow-xl border border-stone-100 animate-in zoom-in duration-500">
        <label className="block text-stone-700 font-bold mb-2 text-sm uppercase tracking-wider">Host Name</label>
        <input 
          type="text" 
          className="w-full px-4 py-3 rounded-lg border border-stone-600 bg-stone-700 text-white placeholder-stone-400 focus:border-accent focus:ring-2 focus:ring-accent/20 outline-none transition-all mb-6 text-lg"
          placeholder="e.g. Julia"
          value={hostName}
          onChange={e => setHostName(e.target.value)}
        />
        <button 
          type="submit" 
          disabled={!hostName.trim() || isLoading}
          className="w-full bg-accent hover:bg-accent-hover text-white font-bold py-4 rounded-lg text-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        >
          {isLoading ? 'Creating...' : 'Start Planning'}
        </button>
      </form>
    </div>
  );
};

// --- Host View ---
const HostPartyView = () => {
  const { partyId } = useParams<{partyId: string}>();
  const [party, setParty] = useState<PartyState | null>(getParty(partyId));
  const [loading, setLoading] = useState(true);
  
  useEffect(() => {
    if (!partyId) return;
    const unsub = subscribeToParty(partyId, () => {
      setParty(getParty(partyId));
      setLoading(false);
    });
    return unsub;
  }, [partyId]);

  if (loading) return <div className="text-center py-20">Loading party details...</div>;

  if (!party) {
    return (
      <div className="text-center p-10 text-stone-500">
        <h2 className="text-xl font-bold mb-2">Party Not Found</h2>
        <p>It looks like this party doesn't exist.</p>
      </div>
    );
  }

  return <HostDashboard party={party} />;
};

// --- Guest View ---
const GuestPartyView = () => {
  const { partyId } = useParams<{partyId: string}>();
  const navigate = useNavigate();
  const [party, setParty] = useState<PartyState | null>(getParty(partyId));
  const [guestName, setGuestName] = useState('');
  const [currentGuest, setCurrentGuest] = useState<Guest | null>(null);
  const [loading, setLoading] = useState(true);
  const [joining, setJoining] = useState(false);

  useEffect(() => {
    if (!partyId) return;
    const unsub = subscribeToParty(partyId, () => {
      setParty(getParty(partyId));
      setLoading(false);
    });
    return unsub;
  }, [partyId]);

  if (loading) return <div className="text-center py-20">Loading party details...</div>;

  if (!party) {
    return (
        <div className="text-center py-20 bg-white rounded-xl shadow-sm max-w-2xl mx-auto mt-10">
            <div className="text-accent mb-4 flex justify-center"><Info size={48} /></div>
            <h2 className="text-3xl font-serif font-bold text-stone-800 mb-4">Party Not Found</h2>
            <p className="text-stone-600 max-w-lg mx-auto mb-8 text-lg leading-relaxed">
                Check the link and try again.
            </p>
            <button onClick={() => navigate('/')} className="px-6 py-3 bg-stone-800 text-white rounded-lg font-bold hover:bg-black transition-colors">Go Home</button>
        </div>
    );
  }

  const handleJoin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!guestName.trim()) return;
    setJoining(true);
    try {
      if (partyId) {
        const guest = await joinParty(partyId, guestName);
        setCurrentGuest(guest);
      }
    } catch (err) {
      console.error(err);
      alert("Could not join party. Please try again.");
    } finally {
      setJoining(false);
    }
  };

  if (!currentGuest) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <div className="max-w-md w-full bg-white p-8 rounded-2xl shadow-xl border border-stone-100 text-center">
          <h2 className="font-serif text-3xl font-bold text-stone-800 mb-2">You're Invited!</h2>
          <p className="text-stone-500 mb-8">
            <strong className="text-stone-800">{party.hostName}</strong> is hosting a charcuterie party and wants your input.
          </p>
          <form onSubmit={handleJoin}>
            <label className="block text-left text-stone-700 font-bold mb-2 text-sm uppercase">Your Name</label>
            <input 
              type="text" 
              className="w-full px-4 py-3 rounded-lg border border-stone-300 focus:border-accent focus:ring-2 focus:ring-accent/20 outline-none transition-all mb-6"
              placeholder="Enter your name"
              value={guestName}
              onChange={e => setGuestName(e.target.value)}
            />
            <button 
              type="submit" 
              disabled={!guestName.trim() || joining}
              className="w-full bg-accent hover:bg-accent-hover text-white font-bold py-3 rounded-lg transition-colors"
            >
              {joining ? 'Joining...' : 'Join & Vote'}
            </button>
          </form>
        </div>
      </div>
    );
  }

  return <GuestVoting party={party} guest={currentGuest} />;
};

const App = () => {
  return (
    <HashRouter>
      <Layout>
        <Routes>
          <Route path="/" element={<Landing />} />
          <Route path="/party/:partyId" element={<HostPartyView />} />
          <Route path="/vote/:partyId" element={<GuestPartyView />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </Layout>
    </HashRouter>
  );
};

export default App;